
import { SRDSpell } from '../../types';

export const CANTRIPS: Record<string, SRDSpell> = {
  acidSplash: {
    id: "acid_splash",
    name: "Acid Splash",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You create an acidic bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere must succeed on a Dexterity saving throw or take 1d6 Acid damage. The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    damage: { diceExpression: "1d6", damageType: "acid", scalingDice: "1d6" },
    savingThrow: { ability: "DEX", dc: 0 },
    areaShape: "sphere", areaSize: 5,
    concentration: false, ritual: false,
    classes: ["Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "acid", "aoe"]
  },
  chillTouch: {
    id: "chill_touch",
    name: "Chill Touch",
    level: 0,
    school: "Necromancy",
    castingTime: "1 Action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Channeling the chill of the grave, make a melee spell attack against a target within reach. On a hit, the target takes 1d10 Necrotic damage, and it can't regain Hit Points until the end of your next turn. The damage increases by 1d10 when you reach levels 5 (2d10), 11 (3d10), and 17 (4d10).",
    damage: { diceExpression: "1d10", damageType: "necrotic", scalingDice: "1d10" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "necrotic", "debuff"],
    statusEffect: "chill_touch"
  },
  dancingLights: {
    id: "dancing_lights",
    name: "Dancing Lights",
    level: 0,
    school: "Illusion",
    castingTime: "1 Action",
    range: "120 feet",
    components: ["V", "S", "M"],
    materialComponent: "a bit of phosphorus",
    duration: "Concentration, up to 1 minute",
    description: "You create up to four torch-size lights within range, making them appear as torches, lanterns, or glowing orbs. Alternatively, you combine them into one glowing Medium form. Whichever form you choose, each light sheds Dim Light in a 10-foot radius. As a Bonus Action, you can move the lights up to 60 feet.",
    concentration: true, ritual: false,
    classes: ["Bard", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "light"]
  },
  druidcraft: {
    id: "druidcraft",
    name: "Druidcraft",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Whispering to the spirits of nature, you create one of the following effects: Weather Sensor (predict weather), Bloom (make flower bloom/seed open), Sensory Effect (falling leaves, breeze, animal sound), or Fire Play (light/snuff candle or campfire).",
    concentration: false, ritual: false,
    classes: ["Druid"],
    source: "SRD 5.2",
    tags: ["utility", "nature"]
  },
  eldritchBlast: {
    id: "eldritch_blast",
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You hurl a beam of crackling energy. Make a ranged spell attack against one creature or object in range. On a hit, the target takes 1d10 Force damage. The spell creates more beams at higher levels: two at 5th, three at 11th, and four at 17th level.",
    damage: { diceExpression: "1d10", damageType: "force", scalingDice: "1d10" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Warlock"],
    source: "SRD 5.2",
    tags: ["damage", "force"]
  },
  elementalism: {
    id: "elementalism",
    name: "Elementalism",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You exert control over the elements: Beckon Air (breeze), Beckon Earth (dust shroud/writing), Beckon Fire (smoke/embers), Beckon Water (mist/cup of water), or Sculpt Element (shape dirt/fire/water in 1ft cube).",
    concentration: false, ritual: false,
    classes: ["Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "elemental"]
  },
  fireBolt: {
    id: "fire_bolt",
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You hurl a mote of fire at a creature or an object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 Fire damage. A flammable object hit by this spell starts burning if it isn't being worn or carried. Damage increases by 1d10 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d10", damageType: "fire", scalingDice: "1d10" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "fire"]
  },
  guidance: {
    id: "guidance",
    name: "Guidance",
    level: 0,
    school: "Divination",
    castingTime: "1 Action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description: "You touch a willing creature and choose a skill. Until the spell ends, the creature adds 1d4 to any ability check using the chosen skill.",
    concentration: true, ritual: false,
    classes: ["Cleric", "Druid"],
    source: "SRD 5.2",
    tags: ["buff", "ability_check"],
    statusEffect: "guidance"
  },
  light: {
    id: "light",
    name: "Light",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    components: ["V", "M"],
    materialComponent: "a firefly or phosphorescent moss",
    duration: "1 hour",
    description: "You touch one Large or smaller object. Until the spell ends, the object sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet.",
    concentration: false, ritual: false,
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "light"]
  },
  mageHand: {
    id: "mage_hand",
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "1 minute",
    description: "A spectral, floating hand appears at a point you choose within range. You can use the hand to manipulate an object, open an unlocked door, stow or retrieve an item, or pour a vial. It can't attack, activate magic items, or carry more than 10 pounds.",
    concentration: false, ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "manipulation"]
  },
  mending: {
    id: "mending",
    name: "Mending",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Minute",
    range: "Touch",
    components: ["V", "S", "M"],
    materialComponent: "two lodestones",
    duration: "Instantaneous",
    description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin (up to 1 foot dimension).",
    concentration: false, ritual: false,
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "repair"]
  },
  message: {
    id: "message",
    name: "Message",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 feet",
    components: ["S", "M"],
    materialComponent: "a copper wire",
    duration: "1 round",
    description: "You point toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear.",
    concentration: false, ritual: false,
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["communication"]
  },
  minorIllusion: {
    id: "minor_illusion",
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["S", "M"],
    materialComponent: "a bit of fleece",
    duration: "1 minute",
    description: "You create a sound or an image of an object within range that lasts for the duration. The image must be no larger than a 5-foot Cube. Physical interaction reveals it to be an illusion.",
    concentration: false, ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility", "illusion"]
  },
  poisonSpray: {
    id: "poison_spray",
    name: "Poison Spray",
    level: 0,
    school: "Necromancy",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You spray toxic mist at a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d12 Poison damage. Damage increases by 1d12 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d12", damageType: "poison", scalingDice: "1d12" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Druid", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "poison"]
  },
  prestidigitation: {
    id: "prestidigitation",
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Action",
    range: "10 feet",
    components: ["V", "S"],
    duration: "Up to 1 hour",
    description: "You create a magical effect: Sensory Effect (sparks, wind, music, odor), Fire Play (light/snuff candle), Clean or Soil (1 cubic foot), Minor Sensation (chill/warm/flavor), Magic Mark, or Minor Creation (nonmagical trinket).",
    concentration: false, ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["utility"]
  },
  produceFlame: {
    id: "produce_flame",
    name: "Produce Flame",
    level: 0,
    school: "Conjuration",
    castingTime: "1 Bonus Action",
    range: "Self",
    components: ["V", "S"],
    duration: "10 minutes",
    description: "A flickering flame appears in your hand. It sheds Bright Light in a 20-foot radius. You can take a Magic action to hurl fire at a creature within 60 feet. Make a ranged spell attack. On a hit, the target takes 1d8 Fire damage. Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "fire", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Druid"],
    source: "SRD 5.2",
    tags: ["damage", "fire", "light"]
  },
  rayOfFrost: {
    id: "ray_of_frost",
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "A frigid beam of blue-white light streaks toward a creature. Make a ranged spell attack. On a hit, it takes 1d8 Cold damage, and its Speed is reduced by 10 feet until the start of your next turn. Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "cold", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "cold", "debuff"],
    statusEffect: "ray_of_frost"
  },
  resistance: {
    id: "resistance",
    name: "Resistance",
    level: 0,
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Concentration, up to 1 minute",
    description: "You touch a willing creature and choose a damage type (Acid, Bludgeoning, Cold, Fire, Lightning, Necrotic, Piercing, Poison, Radiant, Slashing, or Thunder). When the creature takes damage of that type, it reduces the total damage by 1d4 (once per turn).",
    concentration: true, ritual: false,
    classes: ["Cleric", "Druid"],
    source: "SRD 5.2",
    tags: ["buff", "defense"]
  },
  sacredFlame: {
    id: "sacred_flame",
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature. The target must succeed on a Dexterity saving throw or take 1d8 Radiant damage. The target gains no benefit from Half Cover or Three-Quarters Cover. Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "radiant", scalingDice: "1d8" },
    savingThrow: { ability: "DEX", dc: 0 },
    concentration: false, ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.2",
    tags: ["damage", "radiant"]
  },
  shillelagh: {
    id: "shillelagh",
    name: "Shillelagh",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Bonus Action",
    range: "Self",
    components: ["V", "S", "M"],
    materialComponent: "mistletoe",
    duration: "1 minute",
    description: "A Club or Quarterstaff you are holding is imbued with nature's power. You can use your spellcasting ability instead of Strength for attack and damage rolls. The damage die becomes a d8. Damage type can be Force. Damage increases at levels 5 (d10), 11 (d12), and 17 (2d6).",
    concentration: false, ritual: false,
    classes: ["Druid"],
    source: "SRD 5.2",
    tags: ["buff", "weapon"],
    statusEffect: "shillelagh"
  },
  shockingGrasp: {
    id: "shocking_grasp",
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Lightning springs from you to a creature. Make a melee spell attack. On a hit, the target takes 1d8 Lightning damage, and it can't make Opportunity Attacks until the start of its next turn. Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "lightning", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Sorcerer", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "lightning", "debuff"]
  },
  sorcerousBurst: {
    id: "sorcerous_burst",
    name: "Sorcerous Burst",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You cast sorcerous energy at one creature or object. Make a ranged spell attack. Hit: 1d8 damage (choose Acid, Cold, Fire, Lightning, Poison, Psychic, or Thunder). If you roll an 8 on a d8, you can roll another d8 and add it (max dice = spellcasting mod). Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "variable", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Sorcerer"],
    source: "SRD 5.2",
    tags: ["damage", "variable"]
  },
  spareTheDying: {
    id: "spare_the_dying",
    name: "Spare the Dying",
    level: 0,
    school: "Necromancy",
    castingTime: "1 Action",
    range: "15 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "Choose a creature within range that has 0 Hit Points and isn't dead. The creature becomes Stable. Range increases at levels 5 (30ft), 11 (60ft), and 17 (120ft).",
    concentration: false, ritual: false,
    classes: ["Cleric", "Druid"],
    source: "SRD 5.2",
    tags: ["healing"]
  },
  starryWisp: {
    id: "starry_wisp",
    name: "Starry Wisp",
    level: 0,
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    components: ["V", "S"],
    duration: "Instantaneous",
    description: "You launch a mote of light. Make a ranged spell attack. Hit: 1d8 Radiant damage, and until the end of your next turn, it emits Dim Light in a 10-foot radius and can't benefit from the Invisible condition. Damage increases by 1d8 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d8", damageType: "radiant", scalingDice: "1d8" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Bard", "Druid"],
    source: "SRD 5.2",
    tags: ["damage", "radiant", "debuff"]
  },
  thaumaturgy: {
    id: "thaumaturgy",
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    components: ["V"],
    duration: "Up to 1 minute",
    description: "You manifest a minor wonder: Altered Eyes, Booming Voice, Fire Play, Invisible Hand (slam/open door), Phantom Sound, or Tremors.",
    concentration: false, ritual: false,
    classes: ["Cleric"],
    source: "SRD 5.2",
    tags: ["utility"]
  },
  trueStrike: {
    id: "true_strike",
    name: "True Strike",
    level: 0,
    school: "Divination",
    castingTime: "1 Action",
    range: "Self",
    components: ["S", "M"],
    materialComponent: "a weapon",
    duration: "Instantaneous",
    description: "Guided by magical insight, you make one attack with the weapon used in the casting. Use spellcasting ability for attack/damage. Hit: Attack deals Radiant damage or normal weapon type. Extra Radiant damage at levels 5 (1d6), 11 (2d6), and 17 (3d6).",
    damage: { diceExpression: "0", damageType: "radiant", scalingDice: "1d6" },
    attackRoll: true,
    concentration: false, ritual: false,
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    source: "SRD 5.2",
    tags: ["damage", "combat"],
    statusEffect: "true_strike"
  },
  viciousMockery: {
    id: "vicious_mockery",
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 feet",
    components: ["V"],
    duration: "Instantaneous",
    description: "You unleash a string of insults. Target must succeed on a Wisdom saving throw or take 1d6 Psychic damage and have Disadvantage on the next attack roll it makes before the end of its next turn. Damage increases by 1d6 at levels 5, 11, and 17.",
    damage: { diceExpression: "1d6", damageType: "psychic", scalingDice: "1d6" },
    savingThrow: { ability: "WIS", dc: 0 },
    concentration: false, ritual: false,
    classes: ["Bard"],
    source: "SRD 5.2",
    tags: ["damage", "psychic", "debuff"]
  }
};
