
import { Item } from '../../types';

export const MAGIC_STAFFS: Item[] = [
    { id: 'staff_charming', name: 'Staff of Charming', type: 'magic', rarity: 'rare', cost: 60000, weight: 4, quantity: 1, description: '10 charges. Charm Person (1), Command (1), Comprehend Languages (1). Can forgo save vs Charm.', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' }, spells: [{ name: 'Charm Person', cost: 1 }, { name: 'Command', cost: 1 }, { name: 'Comprehend Languages', cost: 1 }] },
    { id: 'staff_fire', name: 'Staff of Fire', type: 'magic', rarity: 'very_rare', cost: 120000, weight: 4, quantity: 1, description: '10 charges. Burning Hands (1), Fireball (3), Wall of Fire (4). Resistance to Fire.', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' }, resistances: ['fire'], spells: [{ name: 'Burning Hands', cost: 1 }, { name: 'Fireball', cost: 3 }, { name: 'Wall of Fire', cost: 4 }] },
    { id: 'staff_frost', name: 'Staff of Frost', type: 'magic', rarity: 'very_rare', cost: 120000, weight: 4, quantity: 1, description: '10 charges. Cone of Cold (5), Fog Cloud (1), Ice Storm (4), Wall of Ice (4). Resistance to Cold.', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' }, resistances: ['cold'], spells: [{ name: 'Cone of Cold', cost: 5 }, { name: 'Fog Cloud', cost: 1 }, { name: 'Ice Storm', cost: 4 }, { name: 'Wall of Ice', cost: 4 }] },
    { id: 'staff_healing', name: 'Staff of Healing', type: 'magic', rarity: 'rare', cost: 60000, weight: 4, quantity: 1, description: '10 charges. Cure Wounds (1), Lesser Restoration (2), Mass Cure Wounds (5).', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' }, spells: [{ name: 'Cure Wounds', cost: 1 }, { name: 'Lesser Restoration', cost: 2 }, { name: 'Mass Cure Wounds', cost: 5 }] },
    { id: 'staff_magi', name: 'Staff of the Magi', type: 'magic', rarity: 'legendary', cost: 500000, weight: 5, quantity: 1, description: '50 charges. Absorb spells. +2 Spell Attack. Many spells.', spells: [{ name: 'Detect Magic', cost: 0 }, { name: 'Fireball', cost: 7 }, { name: 'Lightning Bolt', cost: 7 }, { name: 'Wall of Fire', cost: 7 }, { name: 'Ice Storm', cost: 9 }, { name: 'Wall of Stone', cost: 9 }, { name: 'Passwall', cost: 11 }, { name: 'Plane Shift', cost: 14 }, { name: 'Telekinesis', cost: 11 }, { name: 'Dispel Magic', cost: 3 }, { name: 'Flaming Sphere', cost: 2 }, { name: 'Invisibility', cost: 2 }, { name: 'Knock', cost: 2 }, { name: 'Web', cost: 2 }, { name: 'Conjure Elemental', cost: 7 }, { name: 'Enlarge/Reduce', cost: 2 }] },
    { id: 'staff_power', name: 'Staff of Power', type: 'magic', rarity: 'very_rare', cost: 250000, weight: 5, quantity: 1, description: '20 charges. +2 AC/Saves/Spell Attack. Fireball, Lightning Bolt, etc.', spells: [{ name: 'Cone of Cold', cost: 5 }, { name: 'Fireball', cost: 5 }, { name: 'Globe of Invulnerability', cost: 6 }, { name: 'Hold Monster', cost: 5 }, { name: 'Levitate', cost: 2 }, { name: 'Lightning Bolt', cost: 5 }, { name: 'Magic Missile', cost: 1 }, { name: 'Ray of Enfeeblement', cost: 1 }, { name: 'Wall of Force', cost: 5 }] },
    { id: 'staff_striking', name: 'Staff of Striking', type: 'magic', rarity: 'very_rare', cost: 100000, weight: 4, quantity: 1, description: '+3 weapon. 10 charges. Expend charge for +1d6 force damage.', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' } },
    { id: 'staff_swarming_insects', name: 'Staff of Swarming Insects', type: 'magic', rarity: 'rare', cost: 60000, weight: 4, quantity: 1, description: '10 charges. Giant Insect (4), Insect Plague (5). Create Insect Cloud.', charges: { current: 10, max: 10, recharge: '1d6+4 at dawn' }, spells: [{ name: 'Giant Insect', cost: 4 }, { name: 'Insect Plague', cost: 5 }] },
    { id: 'staff_thunder_lightning', name: 'Staff of Thunder and Lightning', type: 'magic', rarity: 'very_rare', cost: 120000, weight: 4, quantity: 1, description: '+2 weapon. Properties: Lightning Strike, Thunderclap, Thunder and Lightning, etc.', spells: [{ name: 'Lightning Bolt', cost: 0 }, { name: 'Thunderclap', cost: 0 }, { name: 'Thunderwave', cost: 0 }] },
    { id: 'staff_withering', name: 'Staff of Withering', type: 'magic', rarity: 'rare', cost: 60000, weight: 4, quantity: 1, description: '3 charges. On hit, deal necrotic damage and reduce Strength.', charges: { current: 3, max: 3, recharge: '1d3 at dawn' } },
    { id: 'staff_woodlands', name: 'Staff of the Woodlands', type: 'magic', rarity: 'rare', cost: 100000, weight: 4, quantity: 1, description: '+2 weapon. +2 Spell Attack. Pass without Trace at will. Tree form.', spells: [{ name: 'Animal Friendship', cost: 1 }, { name: 'Awaken', cost: 5 }, { name: 'Barkskin', cost: 2 }, { name: 'Locate Animals or Plants', cost: 2 }, { name: 'Pass without Trace', cost: 2 }, { name: 'Speak with Animals', cost: 1 }, { name: 'Speak with Plants', cost: 3 }, { name: 'Wall of Thorns', cost: 6 }] },
    { id: 'staff_python', name: 'Staff of the Python', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 4, quantity: 1, description: 'Transforms into Giant Constrictor Snake.' }
];
