
import { Item } from '../../types';

export const WONDROUS_ITEMS: Item[] = [
    { id: 'amulet_health', name: 'Amulet of Health', type: 'magic', rarity: 'rare', cost: 60000, weight: 1, quantity: 1, description: 'Con 19.', effect: { type: 'buff', stat: 'con_score', value: '19' } },
    { id: 'amulet_proof_detection', name: 'Amulet of Proof against Detection', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 1, quantity: 1, description: 'Hidden from divination magic.' },
    { id: 'amulet_planes', name: 'Amulet of the Planes', type: 'magic', rarity: 'very_rare', cost: 120000, weight: 1, quantity: 1, description: 'Plane Shift (Int check DC 15).', spells: [{ name: 'Plane Shift', cost: 0 }] },
    { id: 'apparatus_crab', name: 'Apparatus of the Crab', type: 'magic', rarity: 'legendary', cost: 300000, weight: 500, quantity: 1, description: 'Lobster tank vehicle.' },
    { id: 'bag_beans', name: 'Bag of Beans', type: 'magic', rarity: 'rare', cost: 30000, weight: 0.5, quantity: 1, description: 'Plant beans for magical effects.' },
    { id: 'bag_devouring', name: 'Bag of Devouring', type: 'magic', rarity: 'very_rare', cost: 50000, weight: 0.5, quantity: 1, description: 'Cursed bag that eats items and creatures.' },
    { id: 'bag_holding', name: 'Bag of Holding', type: 'magic', rarity: 'uncommon', cost: 40000, weight: 15, quantity: 1, description: 'Holds 500lbs.' },
    { id: 'bag_tricks', name: 'Bag of Tricks', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0.5, quantity: 1, description: 'Pull out fuzzy object -> Animal.' },
    { id: 'bead_force', name: 'Bead of Force', type: 'magic', rarity: 'rare', cost: 10000, weight: 0, quantity: 1, description: 'Explodes into force bubble.' },
    { id: 'bead_nourishment', name: 'Bead of Nourishment', type: 'magic', rarity: 'common', cost: 500, weight: 0, quantity: 1, description: 'Sustains for 1 day.' },
    { id: 'belt_dwarvenkind', name: 'Belt of Dwarvenkind', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: '+2 Con. Darkvision. Poison resist.' },
    { id: 'belt_giant_hill', name: 'Belt of Hill Giant Strength', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: 'Str 21.', effect: { type: 'buff', stat: 'str_score', value: '21' } },
    { id: 'belt_giant_frost', name: 'Belt of Frost Giant Strength', type: 'magic', rarity: 'very_rare', cost: 100000, weight: 1, quantity: 1, description: 'Str 23.', effect: { type: 'buff', stat: 'str_score', value: '23' } },
    { id: 'belt_giant_fire', name: 'Belt of Fire Giant Strength', type: 'magic', rarity: 'very_rare', cost: 120000, weight: 1, quantity: 1, description: 'Str 25.', effect: { type: 'buff', stat: 'str_score', value: '25' } },
    { id: 'belt_giant_cloud', name: 'Belt of Cloud Giant Strength', type: 'magic', rarity: 'legendary', cost: 200000, weight: 1, quantity: 1, description: 'Str 27.', effect: { type: 'buff', stat: 'str_score', value: '27' } },
    { id: 'belt_giant_storm', name: 'Belt of Storm Giant Strength', type: 'magic', rarity: 'legendary', cost: 250000, weight: 1, quantity: 1, description: 'Str 29.', effect: { type: 'buff', stat: 'str_score', value: '29' } },
    { id: 'boat_folding', name: 'Folding Boat', type: 'magic', rarity: 'rare', cost: 30000, weight: 4, quantity: 1, description: 'Box unfolds into boat.' },
    { id: 'boots_elvenkind', name: 'Boots of Elvenkind', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 1, quantity: 1, description: 'Silent steps. Advantage Stealth.' },
    { id: 'boots_levitation', name: 'Boots of Levitation', type: 'magic', rarity: 'rare', cost: 30000, weight: 1, quantity: 1, description: 'Cast Levitate on self at will.', spells: [{ name: 'Levitate', cost: 0 }] },
    { id: 'boots_speed', name: 'Boots of Speed', type: 'magic', rarity: 'rare', cost: 40000, weight: 1, quantity: 1, description: 'Bonus action double speed. Disadv on OA.' },
    { id: 'boots_striding', name: 'Boots of Striding and Springing', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 1, quantity: 1, description: 'Speed 30 (not reduced by armor). 3x Jump.', spells: [{ name: 'Jump', cost: 0 }] },
    { id: 'boots_winterlands', name: 'Boots of the Winterlands', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 1, quantity: 1, description: 'Cold resistance. Ignore ice terrain.' },
    { id: 'bowl_water', name: 'Bowl of Commanding Water Elementals', type: 'magic', rarity: 'rare', cost: 40000, weight: 3, quantity: 1, description: 'Summon Water Elemental.', spells: [{ name: 'Conjure Elemental', cost: 1 }] },
    { id: 'bracers_archery', name: 'Bracers of Archery', type: 'magic', rarity: 'uncommon', cost: 25000, weight: 1, quantity: 1, description: '+2 damage with bows.' },
    { id: 'bracers_defense', name: 'Bracers of Defense', type: 'magic', rarity: 'rare', cost: 60000, weight: 1, quantity: 1, description: '+2 AC if unarmored.', effect: { type: 'buff', stat: 'ac', value: '2' } },
    { id: 'brazier_fire', name: 'Brazier of Commanding Fire Elementals', type: 'magic', rarity: 'rare', cost: 40000, weight: 5, quantity: 1, description: 'Summon Fire Elemental.', spells: [{ name: 'Conjure Elemental', cost: 1 }] },
    { id: 'brooch_shielding', name: 'Brooch of Shielding', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Resistance to Force. Immune to Magic Missile.' },
    { id: 'broom_flying', name: 'Broom of Flying', type: 'magic', rarity: 'uncommon', cost: 50000, weight: 3, quantity: 1, description: 'Fly 50ft.' },
    { id: 'candle_invocation', name: 'Candle of Invocation', type: 'magic', rarity: 'very_rare', cost: 100000, weight: 0, quantity: 1, description: '+2 levels for Cleric/Druid. Gate spell.', spells: [{ name: 'Gate', cost: 1 }] },
    { id: 'cape_mountebank', name: 'Cape of the Mountebank', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: 'Dimension Door 1/day.', spells: [{ name: 'Dimension Door', cost: 1 }] },
    { id: 'carpet_flying', name: 'Carpet of Flying', type: 'magic', rarity: 'very_rare', cost: 80000, weight: 10, quantity: 1, description: 'Fly speed 30-80ft depending on size.' },
    { id: 'censer_air', name: 'Censer of Controlling Air Elementals', type: 'magic', rarity: 'rare', cost: 40000, weight: 1, quantity: 1, description: 'Summon Air Elemental.', spells: [{ name: 'Conjure Elemental', cost: 1 }] },
    { id: 'chime_opening', name: 'Chime of Opening', type: 'magic', rarity: 'rare', cost: 20000, weight: 1, quantity: 1, description: 'Opens locks.', spells: [{ name: 'Knock', cost: 1 }] },
    { id: 'circlet_blasting', name: 'Circlet of Blasting', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Scorching Ray 1/day.', spells: [{ name: 'Scorching Ray', cost: 1 }] },
    { id: 'cloak_arachnida', name: 'Cloak of Arachnida', type: 'magic', rarity: 'very_rare', cost: 80000, weight: 1, quantity: 1, description: 'Spider Climb. Web immunity. Web spell.', spells: [{ name: 'Web', cost: 1 }] },
    { id: 'cloak_displacement', name: 'Cloak of Displacement', type: 'magic', rarity: 'rare', cost: 60000, weight: 1, quantity: 1, description: 'Disadvantage on attacks against you.' },
    { id: 'cloak_elvenkind', name: 'Cloak of Elvenkind', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 1, quantity: 1, description: 'Advantage Stealth. Disadvantage Perception to see you.' },
    { id: 'cloak_protection', name: 'Cloak of Protection', type: 'magic', rarity: 'uncommon', cost: 35000, weight: 1, quantity: 1, description: '+1 AC/Saves.', passiveBonuses: [{ stat: 'ac', value: 1 }, { stat: 'saves', value: 1 }] },
    { id: 'cloak_bat', name: 'Cloak of the Bat', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: 'Advantage Stealth in dim light. Fly 40ft (dim light). Polymorph into bat.', spells: [{ name: 'Polymorph', cost: 1 }] },
    { id: 'cloak_manta', name: 'Cloak of the Manta Ray', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 1, quantity: 1, description: 'Swim speed 60ft. Breathe water.' },
    { id: 'crystal_ball', name: 'Crystal Ball', type: 'magic', rarity: 'very_rare', cost: 100000, weight: 3, quantity: 1, description: 'Scrying.', spells: [{ name: 'Scrying', cost: 0 }] },
    { id: 'cube_force', name: 'Cube of Force', type: 'magic', rarity: 'rare', cost: 60000, weight: 1, quantity: 1, description: 'Creates barriers.', spells: [{ name: 'Wall of Force', cost: 1 }] },
    { id: 'cubic_gate', name: 'Cubic Gate', type: 'magic', rarity: 'legendary', cost: 200000, weight: 1, quantity: 1, description: 'Gate/Plane Shift to 6 planes.', spells: [{ name: 'Gate', cost: 1 }, { name: 'Plane Shift', cost: 1 }] },
    { id: 'decanter_water', name: 'Decanter of Endless Water', type: 'magic', rarity: 'uncommon', cost: 30000, weight: 2, quantity: 1, description: 'Pours water.' },
    { id: 'deck_illusions', name: 'Deck of Illusions', type: 'magic', rarity: 'uncommon', cost: 25000, weight: 0.5, quantity: 1, description: 'Create illusions from cards.', spells: [{ name: 'Major Image', cost: 1 }] },
    { id: 'deck_many_things', name: 'Deck of Many Things', type: 'magic', rarity: 'legendary', cost: 500000, weight: 0, quantity: 1, description: 'Draw cards for chaos.' },
    { id: 'dimensional_shackles', name: 'Dimensional Shackles', type: 'magic', rarity: 'rare', cost: 40000, weight: 2, quantity: 1, description: 'Prevents teleportation.' },
    { id: 'dragon_orb', name: 'Dragon Orb', type: 'magic', rarity: 'legendary', cost: 1000000, weight: 5, quantity: 1, description: 'Control dragons.', spells: [{ name: 'Dominate Monster', cost: 1 }] },
    { id: 'dust_disappearance', name: 'Dust of Disappearance', type: 'magic', rarity: 'uncommon', cost: 5000, weight: 0, quantity: 1, description: 'Invisibility 2d4 minutes.', spells: [{ name: 'Invisibility', cost: 1 }] },
    { id: 'dust_dryness', name: 'Dust of Dryness', type: 'magic', rarity: 'uncommon', cost: 5000, weight: 0, quantity: 1, description: 'Absorbs water.' },
    { id: 'dust_sneezing', name: 'Dust of Sneezing and Choking', type: 'magic', rarity: 'uncommon', cost: 5000, weight: 0, quantity: 1, description: 'Incapacitates/Stuns.' },
    { id: 'efficient_quiver', name: 'Efficient Quiver', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 2, quantity: 1, description: 'Holds ammo/weapons efficiently.' },
    { id: 'efreeti_bottle', name: 'Efreeti Bottle', type: 'magic', rarity: 'very_rare', cost: 150000, weight: 1, quantity: 1, description: 'Trapped Efreeti.' },
    { id: 'elemental_gem', name: 'Elemental Gem', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 0, quantity: 1, description: 'Summon Elemental 1/use (destroyed).', spells: [{ name: 'Conjure Elemental', cost: 1 }] },
    { id: 'eversmoking_bottle', name: 'Eversmoking Bottle', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 1, quantity: 1, description: 'Obscuring smoke cloud.' },
    { id: 'eyes_charming', name: 'Eyes of Charming', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Charm Person 3/day.', spells: [{ name: 'Charm Person', cost: 1 }] },
    { id: 'eyes_eagle', name: 'Eyes of the Eagle', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Advantage Perception.' },
    { id: 'eyes_minute_seeing', name: 'Eyes of Minute Seeing', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Magnification.' },
    { id: 'feather_token', name: 'Feather Token', type: 'magic', rarity: 'rare', cost: 5000, weight: 0, quantity: 1, description: 'One-use magical effect (Bird, Tree, Whip, etc.).' },
    { id: 'figurine_wondrous', name: 'Figurine of Wondrous Power', type: 'magic', rarity: 'rare', cost: 30000, weight: 1, quantity: 1, description: 'Becomes animal.' },
    { id: 'gauntlets_ogre', name: 'Gauntlets of Ogre Power', type: 'magic', rarity: 'uncommon', cost: 30000, weight: 2, quantity: 1, description: 'Str 19.', effect: { type: 'buff', stat: 'str_score', value: '19' } },
    { id: 'gem_brightness', name: 'Gem of Brightness', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Blinds creatures.' },
    { id: 'gem_seeing', name: 'Gem of Seeing', type: 'magic', rarity: 'rare', cost: 60000, weight: 0, quantity: 1, description: 'Truesight.', spells: [{ name: 'True Seeing', cost: 1 }] },
    { id: 'gloves_missile', name: 'Gloves of Missile Snaring', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Reduce damage from ranged weapon attacks.' },
    { id: 'gloves_swimming', name: 'Gloves of Swimming and Climbing', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Climb/Swim speeds.' },
    { id: 'gloves_thievery', name: 'Gloves of Thievery', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: '+5 Sleight of Hand/Lockpicking.' },
    { id: 'goggles_night', name: 'Goggles of Night', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Darkvision 60ft.' },
    { id: 'handy_haversack', name: 'Handy Haversack', type: 'magic', rarity: 'rare', cost: 50000, weight: 5, quantity: 1, description: 'Holds items, always weighs 5lbs.' },
    { id: 'hat_disguise', name: 'Hat of Disguise', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Disguise Self at will.', spells: [{ name: 'Disguise Self', cost: 0 }] },
    { id: 'headband_intellect', name: 'Headband of Intellect', type: 'magic', rarity: 'uncommon', cost: 50000, weight: 1, quantity: 1, description: 'Int 19.', effect: { type: 'buff', stat: 'int_score', value: '19' } },
    { id: 'helm_brilliance', name: 'Helm of Brilliance', type: 'magic', rarity: 'very_rare', cost: 200000, weight: 3, quantity: 1, description: 'Fire resistance, light, spells.', spells: [{ name: 'Daylight', cost: 0 }, { name: 'Fireball', cost: 1 }, { name: 'Prismatic Spray', cost: 1 }, { name: 'Wall of Fire', cost: 1 }] },
    { id: 'helm_comprehending', name: 'Helm of Comprehending Languages', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 3, quantity: 1, description: 'Understand languages.', spells: [{ name: 'Comprehend Languages', cost: 0 }] },
    { id: 'helm_telepathy', name: 'Helm of Telepathy', type: 'magic', rarity: 'uncommon', cost: 25000, weight: 2, quantity: 1, description: 'Detect Thoughts/Suggestion.', spells: [{ name: 'Detect Thoughts', cost: 0 }, { name: 'Suggestion', cost: 1 }] },
    { id: 'helm_teleportation', name: 'Helm of Teleportation', type: 'magic', rarity: 'rare', cost: 60000, weight: 3, quantity: 1, description: 'Teleport 3/day.', spells: [{ name: 'Teleport', cost: 1 }] },
    { id: 'horn_blasting', name: 'Horn of Blasting', type: 'magic', rarity: 'rare', cost: 40000, weight: 2, quantity: 1, description: '5d6 Thunder damage cone.' },
    { id: 'horn_valhalla', name: 'Horn of Valhalla', type: 'magic', rarity: 'rare', cost: 50000, weight: 2, quantity: 1, description: 'Summon Berserkers.' },
    { id: 'horseshoes_speed', name: 'Horseshoes of Speed', type: 'magic', rarity: 'rare', cost: 30000, weight: 10, quantity: 1, description: '+30ft speed for horse.' },
    { id: 'horseshoes_zephyr', name: 'Horseshoes of a Zephyr', type: 'magic', rarity: 'very_rare', cost: 60000, weight: 10, quantity: 1, description: 'Hover, ignore terrain.' },
    { id: 'instant_fortress', name: 'Instant Fortress', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: 'Expands into tower.' },
    { id: 'ioun_stone', name: 'Ioun Stone', type: 'magic', rarity: 'rare', cost: 50000, weight: 0, quantity: 1, description: 'Various stat boosts or absorption.' },
    { id: 'iron_bands', name: 'Iron Bands', type: 'magic', rarity: 'rare', cost: 40000, weight: 1, quantity: 1, description: 'Restrain creature.' },
    { id: 'iron_flask', name: 'Iron Flask', type: 'magic', rarity: 'legendary', cost: 200000, weight: 1, quantity: 1, description: 'Capture creature.' },
    { id: 'lantern_revealing', name: 'Lantern of Revealing', type: 'magic', rarity: 'uncommon', cost: 30000, weight: 2, quantity: 1, description: 'Reveal invisible.' },
    { id: 'manual_golems', name: 'Manual of Golems', type: 'magic', rarity: 'very_rare', cost: 100000, weight: 5, quantity: 1, description: 'Create Golem.' },
    { id: 'manual_stats', name: 'Manual of Bodily Health', type: 'magic', rarity: 'very_rare', cost: 200000, weight: 5, quantity: 1, description: '+2 Con (and max).' },
    { id: 'marvelous_pigments', name: 'Marvelous Pigments', type: 'magic', rarity: 'very_rare', cost: 50000, weight: 1, quantity: 1, description: 'Paint real objects.' },
    { id: 'medallion_thoughts', name: 'Medallion of Thoughts', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Detect Thoughts.', spells: [{ name: 'Detect Thoughts', cost: 1 }] },
    { id: 'mirror_life_trapping', name: 'Mirror of Life Trapping', type: 'magic', rarity: 'very_rare', cost: 200000, weight: 50, quantity: 1, description: 'Trap creatures.' },
    { id: 'necklace_adaptation', name: 'Necklace of Adaptation', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Breathe anywhere.' },
    { id: 'necklace_fireballs', name: 'Necklace of Fireballs', type: 'magic', rarity: 'rare', cost: 40000, weight: 1, quantity: 1, description: 'Throw bead for Fireball.', spells: [{ name: 'Fireball', cost: 1 }] },
    { id: 'necklace_prayer_beads', name: 'Necklace of Prayer Beads', type: 'magic', rarity: 'rare', cost: 50000, weight: 1, quantity: 1, description: 'Cast bonus action spells.', spells: [{ name: 'Bless', cost: 1 }, { name: 'Cure Wounds', cost: 1 }, { name: 'Lesser Restoration', cost: 1 }, { name: 'Greater Restoration', cost: 1 }, { name: 'Branding Smite', cost: 1 }, { name: 'Planar Ally', cost: 1 }, { name: 'Wind Walk', cost: 1 }] },
    { id: 'pearl_power', name: 'Pearl of Power', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: 'Regain 3rd level slot.' },
    { id: 'periapt_health', name: 'Periapt of Health', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Immune to disease.' },
    { id: 'periapt_poison', name: 'Periapt of Proof against Poison', type: 'magic', rarity: 'rare', cost: 30000, weight: 0, quantity: 1, description: 'Immunity to Poison.' },
    { id: 'periapt_wound_closure', name: 'Periapt of Wound Closure', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Stabilize auto. Double hit dice heal.' },
    { id: 'pipes_haunting', name: 'Pipes of Haunting', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 2, quantity: 1, description: 'Frighten creatures.' },
    { id: 'pipes_sewers', name: 'Pipes of the Sewers', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 2, quantity: 1, description: 'Summon rat swarms.' },
    { id: 'portable_hole', name: 'Portable Hole', type: 'magic', rarity: 'rare', cost: 50000, weight: 0, quantity: 1, description: '6ft diameter hole to extradimensional space.' },
    { id: 'robe_archmagi', name: 'Robe of the Archmagi', type: 'magic', rarity: 'legendary', cost: 300000, weight: 3, quantity: 1, description: 'AC 15+Dex. Adv vs Spells. +2 DC/Attack.' },
    { id: 'robe_eyes', name: 'Robe of Eyes', type: 'magic', rarity: 'rare', cost: 50000, weight: 3, quantity: 1, description: '360 vision. See invisible.' },
    { id: 'robe_scintillating', name: 'Robe of Scintillating Colors', type: 'magic', rarity: 'very_rare', cost: 60000, weight: 3, quantity: 1, description: 'Stun/Blind nearby.' },
    { id: 'robe_stars', name: 'Robe of Stars', type: 'magic', rarity: 'very_rare', cost: 80000, weight: 3, quantity: 1, description: 'Magic Missile. Astral Plane.', spells: [{ name: 'Magic Missile', cost: 0 }] },
    { id: 'robe_useful', name: 'Robe of Useful Items', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 3, quantity: 1, description: 'Pull items from patches.' },
    { id: 'rope_climbing', name: 'Rope of Climbing', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 3, quantity: 1, description: 'Animates to climb.' },
    { id: 'rope_entanglement', name: 'Rope of Entanglement', type: 'magic', rarity: 'rare', cost: 30000, weight: 3, quantity: 1, description: 'Entangle creature.', spells: [{ name: 'Entangle', cost: 1 }] },
    { id: 'scarab_protection', name: 'Scarab of Protection', type: 'magic', rarity: 'legendary', cost: 150000, weight: 0, quantity: 1, description: 'Advantage vs Spells. Protect vs Necromancy.' },
    { id: 'sending_stones', name: 'Sending Stones', type: 'magic', rarity: 'uncommon', cost: 10000, weight: 0, quantity: 1, description: 'Communicate.', spells: [{ name: 'Sending', cost: 1 }] },
    { id: 'sovereign_glue', name: 'Sovereign Glue', type: 'magic', rarity: 'legendary', cost: 100000, weight: 1, quantity: 1, description: 'Permanent bond.' },
    { id: 'sphere_annihilation', name: 'Sphere of Annihilation', type: 'magic', rarity: 'legendary', cost: 500000, weight: 0, quantity: 1, description: 'Black hole.' },
    { id: 'stone_earth', name: 'Stone of Controlling Earth Elementals', type: 'magic', rarity: 'rare', cost: 40000, weight: 5, quantity: 1, description: 'Summon Earth Elemental.', spells: [{ name: 'Conjure Elemental', cost: 1 }] },
    { id: 'stone_luck', name: 'Stone of Good Luck', type: 'magic', rarity: 'uncommon', cost: 20000, weight: 0, quantity: 1, description: '+1 Checks/Saves.', passiveBonuses: [{ stat: 'checks', value: 1 }, { stat: 'saves', value: 1 }] },
    { id: 'talisman_pure_good', name: 'Talisman of Pure Good', type: 'magic', rarity: 'legendary', cost: 300000, weight: 0, quantity: 1, description: 'Destroy evil.' },
    { id: 'universal_solvent', name: 'Universal Solvent', type: 'magic', rarity: 'legendary', cost: 50000, weight: 0, quantity: 1, description: 'Dissolves Sovereign Glue.' },
    { id: 'well_many_worlds', name: 'Well of Many Worlds', type: 'magic', rarity: 'legendary', cost: 250000, weight: 0, quantity: 1, description: 'Portal to random plane.' },
    { id: 'wind_fan', name: 'Wind Fan', type: 'magic', rarity: 'uncommon', cost: 15000, weight: 0, quantity: 1, description: 'Gust of Wind.', spells: [{ name: 'Gust of Wind', cost: 1 }] },
    { id: 'winged_boots', name: 'Winged Boots', type: 'magic', rarity: 'uncommon', cost: 40000, weight: 1, quantity: 1, description: 'Fly speed.', effect: { type: 'buff', value: 'flying', duration: 600 } },
    { id: 'wings_flying', name: 'Wings of Flying', type: 'magic', rarity: 'rare', cost: 50000, weight: 2, quantity: 1, description: 'Fly 60ft.' }
];
